# FIRS - DATA ANALYSIS AND STORYTELLING

## First data visualizations
<i>Vega-Altair ; Panda ; Plotly</i>

In these exercises, you will create first visualizations of the data distribution in table datasets.
You will work with ARBRES.csv, ECOLOGIE.csv and PLACETTE.csv datasets. The first one contains data on trees located on various measurement sites for different measurement campaigns. The second one contains data related to several ecological indicators, for each measurement sites, for different measurement campaigns. The third one contains data related to the measurement sites themselves.
You will use the [Pandas](https://pandas.pydata.org/) module for all data processing operations, as well as two data visualization modules: [Vega-Altair](https://altair-viz.github.io/index.html) and [Plotly](https://plotly.com/python/).

In [1]:
import pandas #importing pandas
import altair #importing altair
altair.data_transformers.enable("vegafusion") # this command allows vega-altair to deal with relatively massive data (up to 100 000 individuals)

DataTransformerRegistry.enable('vegafusion')

In [2]:
datafile = r".\data\Arbre.csv" #locating Arbre.csv dataset on your computer
df = pandas.read_csv(datafile,sep=';') #importing Arbre.csv dataset into a Pandas dataframe
df_2015 = df.loc[df['CAMPAGNE'] == 2015] #creating another dataframe by extracting all data from Arbre.csv for the 2005 measurement campaign

C:\Users\JGautier.IGN\AppData\Local\Temp\ipykernel_36956\3096970808.py:2: DtypeWarning: Columns (0: VEGET, 1: VEGET5, 2: FORME, 3: QUALITE, 4: CLON, 5: MORTB, 6: MA, 7: MR) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pandas.read_csv(datafile,sep=';') #importing Arbre.csv dataset into a Pandas dataframe

### Create visualizations with Vega-Altair

#### What is Vega-Altair?

We will mainly use here the [Vega-Altair](https://altair-viz.github.io/) module to create visualizations. Altair is a python module adapted from the [Vega](https://vega.github.io/vega/) javascript library. Vega (and its lighter version Vega-Lite) is a framework based on Leland Wilkinson's Grammar of Graphics for creating SVG visualizations using [D3](https://d3js.org/) JavaScript library. Vega offers a declarative language for creating visualizations; they use a visualization grammar structured in JSON format, where we define the graphical layout (the <b>mark</b>) of the symbols representing our data, and the visual channels used for representing the information (the <b>encoding</b>). Based on these definitions — which specify which data components to visualize and how — the corresponding visualization is generated in SVG format using D3 (other outputs can be specified: png, canvas,...). Vega-Altair follows the same logic, being a declarative visualization API-based enabling the creation of simple visualizations without the need for complex coding. You can find various examples [here](https://altair-viz.github.io/gallery/index.html#example-gallery). The first step is to install Altair and import it on your notebook.

#### How it works?

In the following code lines, we define the parameters of a visualization representing the distribution according to one variable.

We specify a type of [mark](https://altair-viz.github.io/user_guide/marks/index.html), which define which kind of graphic object will be used for our visualization's symbols.

We specify an [encoding](https://altair-viz.github.io/user_guide/encodings/index.html), which define which symbols' visual channel will be used to represent the information, and how it will be represented. When defining an encoding, we must specify what information or constant value that encoding represents. This can be a dataset attribute, a constant graphical value, a specific value linked to the dataset. For each attribute variable defined in the encoding, we specify the type of variable being represented. There are 5 types: quantitative, ordinal, nominal (categorical), temporal, and GeoJSON for geographic data in GeoJSON format.
Depending on the type selected to describe the attribute, the chosen visual variable will be used differently to encode the information; for example, the color scale applied will differ depending on whether an attribute is specified as categorical or ordinal.

In [3]:
altair.Chart(df_2015).mark_tick(size=60).encode(
    altair.X('V', type='quantitative')
).properties(
    width=1000
)

alt.Chart(...)

#### Vega or another thing?

All Vega components are a good introduction materials for visualization conception, since it is focused on the declaration of visualization specifications. 
However, some complex visualizations are difficult to be created with Vega. For such kind of visualization, a more complex solution is necessary ([D3](https://d3js.org/), [Matplotlib](https://matplotlib.org/), [Plotly](https://plotly.com/python/), etc).  

Vega-Altair is only able to deal with not-to-massive datasets (up to 100 000 individuals). If you have to deal with massive datasets, other modules such as Matplotlib or Plotly are necessary. 

On each exercices, you will find additionnal questions ("Going Further") which propose more complex challenges, with Plotly (or Matplotly if you prefer). Only do these questions if you are in advance in comparison with the others.

#### Conception before implementation

In some exercises, you will be asked to propose visualization approaches to address a specific problem. You can consult Vega-Alair documentation—or even the website https://www.data-to-viz.com/ to find a suitable visualization.

### EXERCICE 1: Visualizing correlations in tables

1. Using tables arbre and ecologie, put in the same table the volume of wood and mean slope by measurement site, for the year 2015.
2. Suggest a chart type from https://www.data-to-viz.com/ that allows you to visualize the relationship between the wood volume and site mean slope, for the year 2015, and implement it using Vega-Alair.
3. Discuss this visualization. How would you add additional information related to other variables?
4. Try to reduce the visual clutter by using this approach: https://www.data-to-viz.com/graph/density2d.html.
5. Which visual channels would you use instead in the previous visualization in order to enhance user's perception? Try it. Suggest another way to reduce cluttering from the example.
6. <b>Going further:</b> Using layers, try to add to the precedent visualization the difference between PROF2 and PROF1, using color. 
7. <b>Going further:</b> Add some interaction on the visualization created on the question 6, in order to display the number of individuals represented by each symbol (https://altair-viz.github.io/user_guide/generated/channels/altair.Tooltip.html#).
8. <b>Going further:</b> In order to show correlations according to multiple variables, try to create a [parallel coordinate chart](https://www.data-to-viz.com/graph/parallel.html) with plotly. What could be added to this visualization to enhance visual analysis?

##### Question 1

In [4]:
df_2015['Vpondere'] = df_2015.V * df_2015.W
df_2015 = df_2015.dropna(subset=['Vpondere'])
V_by_spot = df_2015.groupby(['IDP'], sort=True)['Vpondere'].sum()
datafile_ecologie = r".\data\Ecologie.csv" #locating ecologie.csv dataset on your computer
df_eco = pandas.read_csv(datafile_ecologie,sep=';') #importing ecologie.csv dataset into a Pandas dataframe
df_eco_2015 = df_eco.loc[df_eco['CAMPAGNE'] == 2015]
df_eco_2015_V = pandas.merge(df_eco_2015, V_by_spot, on='IDP', how='inner')

C:\Users\JGautier.IGN\AppData\Local\Temp\ipykernel_36956\3912661258.py:5: DtypeWarning: Columns (0: OH, 1: TEXT1, 2: TEXT2, 3: OBSPEDO, 4: AFFROC, 5: CAI40, 6: CAILLOUX, 7: PGLEY, 8: POX, 9: PPSEUDO, 10: PCALC, 11: PCALF) have mixed types. Specify dtype option on import or set low_memory=False.
  df_eco = pandas.read_csv(datafile_ecologie,sep=';') #importing ecologie.csv dataset into a Pandas dataframe

##### Question 2

A scatterplot can be a way to visualize correlations between 2 quantitative variables.

In [5]:
altair.Chart(df_eco_2015_V).mark_circle(size=60).encode(
    altair.X('PENT2', type='quantitative'),
    altair.Y('Vpondere', type='quantitative')
).properties(
    width=500,
    height=500
)

alt.Chart(...)

##### Question 3

The scatterplot is to cluttered to identify clearly a correlation, except for a slight negative effect of slope on the wood volume. 
Color can be used to represent additional variable, but the scatterplot is to cluttered for this to be effective.
One solution could be to filter the dataset.

In [6]:
altair.Chart(df_eco_2015_V).mark_circle(size=60).encode(
    altair.X('PENT2', type='quantitative'),
    altair.Y('Vpondere', type='quantitative'),
    altair.Color('EXPO', type='quantitative').scale(scheme="sinebow")
).properties(
    width=500,
    height=500
)

alt.Chart(...)

##### Question 4

In [7]:
bins = 50

altair.Chart(df_eco_2015_V).mark_rect().encode(
    altair.X('PENT2', type='quantitative').bin(maxbins=bins),
    altair.Y('Vpondere', type='quantitative').bin(maxbins=bins),
    altair.Color("count()").scale(scheme="greenblue")
).properties(
    width=500,
    height=500
)

alt.Chart(...)

##### Question 5
Size can be used in order to represent the number of individuals in a better way than color.
Color can then be used represent another aggregated variable.

Cluttering can be reduced with this approach (https://altair-viz.github.io/gallery/scatter_marginal_hist.html) and filtering.

In [8]:
bins = 50

altair.Chart(df_eco_2015_V).mark_circle().encode(
    altair.X('PENT2', type='quantitative').bin(maxbins=bins),
    altair.Y('Vpondere', type='quantitative').bin(maxbins=bins),
    altair.Size("count()")
).properties(
    width=500,
    height=500
)

alt.Chart(...)

##### Question 6

In [9]:
bins = 50
df_eco_2015_V['diff_prof'] = df_eco_2015_V.PROF2 - df_eco_2015_V.PROF1
points = altair.Chart(df_eco_2015_V).mark_circle(filled=False, color='red').encode(
    altair.X('PENT2', type='quantitative').bin(maxbins=bins),
    altair.Y('Vpondere', type='quantitative').bin(maxbins=bins),
    altair.Size("count()")
).properties(
    width=500,
    height=500
)

heatmap = altair.Chart(df_eco_2015_V).mark_rect().encode(
    altair.X('PENT2', type='quantitative').bin(maxbins=bins),
    altair.Y('Vpondere', type='quantitative').bin(maxbins=bins),
    altair.Color("mean(diff_prof)").scale(scheme="greenblue")
).properties(
    width=500,
    height=500
)

heatmap + points

alt.LayerChart(...)

##### Question 7

In [10]:
bins = 50
df_eco_2015_V['diff_prof'] = df_eco_2015_V.PROF2 - df_eco_2015_V.PROF1
points = altair.Chart(df_eco_2015_V).mark_circle(filled=False, color='red').encode(
    altair.X('PENT2', type='quantitative').bin(maxbins=bins),
    altair.Y('Vpondere', type='quantitative').bin(maxbins=bins),
    altair.Size("count()")
).properties(
    width=500,
    height=500
)

heatmap = altair.Chart(df_eco_2015_V).mark_rect().encode(
    altair.X('PENT2', type='quantitative').bin(maxbins=bins),
    altair.Y('Vpondere', type='quantitative').bin(maxbins=bins),
    altair.Color("mean(diff_prof)").scale(scheme="greenblue"),
    tooltip=[
        altair.Tooltip("PENT2", title="mean slope"),
        altair.Tooltip("Vpondere", title="wood volume"),
        altair.Tooltip("count()", title="number of sites")
    ]
).properties(
    width=500,
    height=500
)

heatmap + points

alt.LayerChart(...)

##### Question 8

This chart could be enhanced by integrating interaction modalities such as the possibility to filter on different axes, and by embedding additional charts to represent distribution for each variable, like in this example: https://hcil.snu.ac.kr/research/parallel-histogram-plots

In [11]:
df_eco_2015_V_PCP = df_eco_2015_V.dropna(subset=['Vpondere','PENT2','diff_prof','EXPO'])
df_eco_2015_V_PCP = df_eco_2015_V_PCP[["Vpondere","PENT2","diff_prof","EXPO"]]
import plotly.express as px
fig = px.parallel_coordinates(df_eco_2015_V_PCP, color="Vpondere", labels={"Vpondere": "Wood volume", "PENT2": "mean slope",
                "diff_prod": "Diff between PROD2 and PROD1", "EXPO": "exposition", },
                             color_continuous_scale=px.colors.diverging.Tealrose,
                             color_continuous_midpoint=500)
fig.show()

### EXERCICE 2: Visualizing data distribution according to a categorical variable.

<i>In this exercice, you will represent information related to trees species. Due to the high number of different species, we will use arbitrary defined categories of species, stored in the following added colums: Type_a, and macro_species. The definition of the different modalities of these two columns is based on the ESPAR column of the ARBRE dataset, storing the code of each tree specy. The meaning of each code is stored in Metadonnees dataset. Since we use data related to the year 2015, we used the ESPAR1 code in the Metadonnees dataset. 

Note: It appears ESPAR codes were not found for a significant number of trees. For the purpose of the exercise, these elements have been filtered out of the dataset. Feel free to try and do better if you have finished. <\i>

In [12]:
#adding Type_a and macro_species columns

df_2015['Type_a'] = ['résineux' if x == '68CE' or x == '68CJ' or x == '64' or x == '68TG' or x == '68TC' or x == '68TH' or x == '68TS' or x == '65' or x == '68CB' or x == '68CH' or x == '76' or x == '66' or x == '68CM' or x == '68CA' or x == '68CL' or x == '68CC' or x == '62' or x == '68EO' or x == '73' or x == '69' or x == '69JC' or x == '69JO' or x == '67' or x == '63' or x == '74J' or x == '74H' or x == '51' or x == '52' or x == '53CO' or x == '53CA' or x == '53S' or x == '54' or x == '55' or x == '56' or x == '57A' or x == '57B' or x == '58' or x == '59' or x == '60' or x == '68PM' or x == '68PC' or x == '77' or x == '61' or x == '68SC' or x == '68SI' or x == '70SE' or x == '70SC' or x == '70SB' or x == '71' or x == '72V' or x == '72N' or x == '68SV' or x == '68SG' else 'Feuillu' if x == '23AB' or x == '23AF' or x == '23AM' or x == '41' or x == '13C' or x == '13G' or x == '13B' or x == '37' or x == '49AA' or x == '49AE' or x == '49AM' or x == '49PA' or x == '29AI' or x == '23A' or x == '40' or x == '49CS' or x == '29AF' or x == '49BO' or x == '49EA' or x == '49BS' or x == '29CA' or x == '29CT' or x == '49CM' or x == '49C' or x == '23C' or x == '39' or x == '38AU' or x == '38AL' or x == '36' or x == '23F' or x == '49FL' or x == '49FA' or x == '29FI' or x == '49EV' or x == '49IA' or x == '49KK' or x == '49LN' or x == '29LI' or x == '49CN' or x == '29MA' or x == '22M' or x == '29MI' or x == '16' or x == '49RA' or x == '49RP' or x == '49RC' or x == '31' or x == '28' or x == '49OB' or x == '49OO' or x == '49CA' or x == '29PT' or x == '29PV' or x == '49PL' or x == '49PT' or x == '29PL' or x == '14' or x == '24' or x == '42' or x == '49VV' or x == '22C' or x == '22G' or x == '22S' or x == '49PM' or x == '49MB' or x == '49MC' or x == '49MN' or x == '23PA' or x == '23PC' or x == '23PF' or x == '49PN' or x == '23PM' or x == '49PC' or x == '49PS' or x == '23PD' or x == '49PB' or x == '49RT' or x == '49SN' or x == '49SR' or x == '11' or x == '32' or x == '10' or x == '27C' or x == '27N' or x == '18C' or x == '18D' or x == '18M' or x == '23SO' or x == '23SF' or x == '23SS' or x == '49TA' or x == '49TF' or x == '49TG' or x == '12P' or x == '12V' or x == '2' or x == '3' or x == '4' or x == '5' or x == '6' or x == '7' or x == '08P' or x == '08S' or x == '29CE' or x == '29CM' or x == '34' or x == '15P' or x == '15S' or x == '21C' or x == '21M' or x == '21O' or x == '29EN' or x == '17C' or x == '17F' or x == '17O' or x == '29FA' or x == '9' or x == '19' or x == '33B' or x == '33G' or x == '33N' or x == '26E' or x == '26OC' or x == '26OR' or x == '25B' or x == '25M' or x == '25C' or x == '25FD' or x == '25FR' or x == '25D' or x == '25P' or x == '2,50E+06' or x == '25XR' or x == '2,50E+04' or x == '25V' or x == '25R' or x == '20P' or x == '20G' or x == '29TA' or x == '29TT' or x == '20X' or x == '29TX' else 'not found' for x in df_2015['ESPAR']]
df_2015['macro_species'] = ['Autre feuillu' if x == '23AB' or x == '23AF' or x == '23AM' or x == '41' or x == '13C' or x == '13G' or x == '13B' or x == '37' or x == '49AA' or x == '49AE' or x == '49AM' or x == '49PA' or x == '29AI' or x == '23A' or x == '40' or x == '49CS' or x == '29AF' or x == '49BO' or x == '49EA' or x == '49BS' or x == '29CA' or x == '29CT' or x == '49CM' or x == '49C' or x == '23C' or x == '39' or x == '38AU' or x == '38AL' or x == '36' or x == '23F' or x == '49FL' or x == '49FA' or x == '29FI' or x == '49EV' or x == '49IA' or x == '49KK' or x == '49LN' or x == '29LI' or x == '49CN' or x == '29MA' or x == '22M' or x == '29MI' or x == '16' or x == '49RA' or x == '49RP' or x == '49RC' or x == '31' or x == '28' or x == '49OB' or x == '49OO' or x == '49CA' or x == '29PT' or x == '29PV' or x == '49PL' or x == '49PT' or x == '29PL' or x == '14' or x == '24' or x == '42' or x == '49VV' or x == '22C' or x == '22G' or x == '22S' or x == '49PM' or x == '49MB' or x == '49MC' or x == '49MN' or x == '23PA' or x == '23PC' or x == '23PF' or x == '49PN' or x == '23PM' or x == '49PC' or x == '49PS' or x == '23PD' or x == '49PB' or x == '49RT' or x == '49SN' or x == '49SR' or x == '11' or x == '32' or x == '10' or x == '27C' or x == '27N' or x == '18C' or x == '18D' or x == '18M' or x == '23SO' or x == '23SF' or x == '23SS' or x == '49TA' or x == '49TF' or x == '49TG' else 'Autre résineux' if x == '68CE' or x == '68CJ' or x == '64' or x == '68TG' or x == '68TC' or x == '68TH' or x == '68TS' or x == '69' or x == '69JC' or x == '69JO' else 'Bouleau' if x == '12P' or x == '12V' else 'Cedre' if x == '65' or x == '68CB' or x == '68CH' or x == '76' else 'Chêne' if x == '2' or x == '3' or x == '4' or x == '5' or x == '6' or x == '7' or x == '08P' or x == '08S' or x == '29CE' or x == '29CM' or x == '34' else 'Cypres' if x == '66' or x == '68CM' or x == '68CA' or x == '68CL' or x == '68CC' else 'Épicéa' if x == '62' or x == '68EO' or x == '73' else 'Érable' if x == '15P' or x == '15S' or x == '21C' or x == '21M' or x == '21O' or x == '29EN' else 'Frêne' if x == '17C' or x == '17F' or x == '17O' or x == '29FA' else 'Hêtre' if x == '9' else 'If' if x == '67' else 'Mélèze' if x == '63' or x == '74J' or x == '74H' else 'Peuplier' if x == '19' or x == '33B' or x == '33G' or x == '33N' else 'Pin' if x == '51' or x == '52' or x == '53CO' or x == '53CA' or x == '53S' or x == '54' or x == '55' or x == '56' or x == '57A' or x == '57B' or x == '58' or x == '59' or x == '60' or x == '68PM' or x == '68PC' or x == '77' else 'Platane' if x == '26E' or x == '26OC' or x == '26OR' else 'Sapin' if x == '61' or x == '68SC' or x == '68SI' or x == '70SE' or x == '70SC' or x == '70SB' or x == '71' or x == '72V' or x == '72N' else 'Saule' if x == '25B' or x == '25M' or x == '25C' or x == '25FD' or x == '25FR' or x == '25D' or x == '25P' or x == '2,50E+06' or x == '25XR' or x == '2,50E+04' or x == '25V' or x == '25R' else 'Séquoia' if x == '68SV' or x == '68SG' else 'Tilleul' if x == '20P' or x == '20G' or x == '29TA' or x == '29TT' or x == '20X' or x == '29TX' else 'not found' for x in df_2015['ESPAR']]
df_2015 = df_2015.loc[df_2015['macro_species'] != 'not found']

1. Suggest a chart to represent the distribution of wood volume according to your first categorization of tree species for the year 2015. Discuss this visualiztion. Propose the same chart for the second categorization. What do you think about this second chart.
2. <b>Going further:</b> Add some interaction on the visualizations created on the question 1, in order to display the wood volume and name of each category. Using this example https://altair-viz.github.io/gallery/interactive_column_selection.html , bring the two precedent charts together. What should be done with the legend?
3. <b>Going further:</b> Using plotly, propose a chart that would combine the two precedent chart, representing the distribution of wood volume according to the two categories at the same time, allowing you to see the relationships between these categories. Add the information regarding the ESPAR code in this visualization.

##### Question 1

The number of categories is to important, especially in order to be represented by color. Grouping categories should be explored. 
The second pie chart is more readable, but we lose a lot of information.

Note: Regarding the error met in the creation of Type_a and macro_species columns, remain suspicious and don't take these outputs as ground truth. The oak wood volume seems very low.

In [13]:
table_by_macro_species = df_2015.groupby(['macro_species'])["Vpondere"].sum().reset_index(name ='TotVolume')
table_by_macro_species

     macro_species      TotVolume
0    Autre feuillu  165907.080532
1   Autre résineux   41572.720845
2          Bouleau   19485.316721
3            Cedre     668.123146
4            Chêne    1156.292220
5           Cypres     229.328723
6            Frêne   46549.188402
7               If      51.184206
8           Mélèze   12187.572029
9         Peuplier   32492.236560
10             Pin  142317.761167
11         Platane      96.114754
12           Sapin   88267.580020
13           Saule    6639.570126
14         Séquoia     112.047749
15         Tilleul    7516.740828
16          Épicéa   83154.829290
17          Érable   21760.089575

In [14]:
altair.Chart(table_by_macro_species).mark_arc().encode(
    theta=altair.Theta(field="TotVolume", type="quantitative"),
    color=altair.Color(field="macro_species", type="nominal"),
)

alt.Chart(...)

In [15]:
table_by_type_a = df_2015.groupby(['Type_a'])["Vpondere"].sum().reset_index(name ='TotVolume')
table_by_type_a

     Type_a      TotVolume
0   Feuillu  301602.629719
1  résineux  368561.147174

In [16]:
altair.Chart(table_by_type_a).mark_arc().encode(
    theta=altair.Theta(field="TotVolume", type="quantitative"),
    color=altair.Color(field="Type_a", type="nominal")
)

alt.Chart(...)

##### Question 2

The legend should be ordered in two categories, for each chart.

In [17]:
chart_by_category = altair.Chart(table_by_macro_species).mark_arc().encode(
    theta=altair.Theta(field="TotVolume", type="quantitative"),
    color=altair.Color(field="macro_species", type="nominal"),
    tooltip=[
        altair.Tooltip("macro_species", title="Species category"),
        altair.Tooltip("TotVolume", title="wood volume")
    ]
)
chart_by_type = altair.Chart(table_by_type_a).mark_arc().encode(
    theta=altair.Theta(field="TotVolume", type="quantitative"),
    color=altair.Color(field="Type_a", type="nominal"),
    tooltip=[
            altair.Tooltip("Type_a", title="Tree type"),
            altair.Tooltip("TotVolume", title="wood volume")
        ]
)
chart_by_category | chart_by_type

alt.HConcatChart(...)

##### Question 3

In [18]:
fig = px.sunburst(df_2015, path=['Type_a', 'macro_species'], values='Vpondere')
fig.show()

In [19]:
fig = px.sunburst(df_2015, path=['Type_a', 'macro_species','ESPAR'], values='Vpondere')
fig.show()

### EXERCICE 3: Visualizing a temporal evolution.

1. Calculate the entire wood volume, for the entire set of measurement sites, for each year of the dataset from 2015.
2. Suggest two kinds of charts to represent the temporal evolution of wood volume through the years. Discuss the pros and cons of the two approaches. Adapt the scale range. How the scale could be improve?
3. Calculate the entire wood volume for each year of the dataset, categorized by the tree species meta-categories that you defined earlier. Propose a multi-line chart, then a stacked area chart and a stacked bar chart, to visualize the temporal evolution of wood volumes according to the different meta-categories. Discuss the pros and cons of the different approaches.
4. <b>Going further:</b> Add some interaction on the visualizations created on the question 3, in order to display the wood volume and name of each category, and to zoom and pan inside the chart.

##### Question 1

In [20]:
df_sup_2015 = df.loc[df['CAMPAGNE'] > 2014] 
df_sup_2015['Vpondere'] = df_sup_2015.V * df_sup_2015.W
df_sup_2015 = df_sup_2015.dropna(subset=['Vpondere'])
df_sup_2015['Type_a'] = ['résineux' if x == '68CE' or x == '68CJ' or x == '64' or x == '68TG' or x == '68TC' or x == '68TH' or x == '68TS' or x == '65' or x == '68CB' or x == '68CH' or x == '76' or x == '66' or x == '68CM' or x == '68CA' or x == '68CL' or x == '68CC' or x == '62' or x == '68EO' or x == '73' or x == '69' or x == '69JC' or x == '69JO' or x == '67' or x == '63' or x == '74J' or x == '74H' or x == '51' or x == '52' or x == '53CO' or x == '53CA' or x == '53S' or x == '54' or x == '55' or x == '56' or x == '57A' or x == '57B' or x == '58' or x == '59' or x == '60' or x == '68PM' or x == '68PC' or x == '77' or x == '61' or x == '68SC' or x == '68SI' or x == '70SE' or x == '70SC' or x == '70SB' or x == '71' or x == '72V' or x == '72N' or x == '68SV' or x == '68SG' else 'Feuillu' if x == '23AB' or x == '23AF' or x == '23AM' or x == '41' or x == '13C' or x == '13G' or x == '13B' or x == '37' or x == '49AA' or x == '49AE' or x == '49AM' or x == '49PA' or x == '29AI' or x == '23A' or x == '40' or x == '49CS' or x == '29AF' or x == '49BO' or x == '49EA' or x == '49BS' or x == '29CA' or x == '29CT' or x == '49CM' or x == '49C' or x == '23C' or x == '39' or x == '38AU' or x == '38AL' or x == '36' or x == '23F' or x == '49FL' or x == '49FA' or x == '29FI' or x == '49EV' or x == '49IA' or x == '49KK' or x == '49LN' or x == '29LI' or x == '49CN' or x == '29MA' or x == '22M' or x == '29MI' or x == '16' or x == '49RA' or x == '49RP' or x == '49RC' or x == '31' or x == '28' or x == '49OB' or x == '49OO' or x == '49CA' or x == '29PT' or x == '29PV' or x == '49PL' or x == '49PT' or x == '29PL' or x == '14' or x == '24' or x == '42' or x == '49VV' or x == '22C' or x == '22G' or x == '22S' or x == '49PM' or x == '49MB' or x == '49MC' or x == '49MN' or x == '23PA' or x == '23PC' or x == '23PF' or x == '49PN' or x == '23PM' or x == '49PC' or x == '49PS' or x == '23PD' or x == '49PB' or x == '49RT' or x == '49SN' or x == '49SR' or x == '11' or x == '32' or x == '10' or x == '27C' or x == '27N' or x == '18C' or x == '18D' or x == '18M' or x == '23SO' or x == '23SF' or x == '23SS' or x == '49TA' or x == '49TF' or x == '49TG' or x == '12P' or x == '12V' or x == '2' or x == '3' or x == '4' or x == '5' or x == '6' or x == '7' or x == '08P' or x == '08S' or x == '29CE' or x == '29CM' or x == '34' or x == '15P' or x == '15S' or x == '21C' or x == '21M' or x == '21O' or x == '29EN' or x == '17C' or x == '17F' or x == '17O' or x == '29FA' or x == '9' or x == '19' or x == '33B' or x == '33G' or x == '33N' or x == '26E' or x == '26OC' or x == '26OR' or x == '25B' or x == '25M' or x == '25C' or x == '25FD' or x == '25FR' or x == '25D' or x == '25P' or x == '2,50E+06' or x == '25XR' or x == '2,50E+04' or x == '25V' or x == '25R' or x == '20P' or x == '20G' or x == '29TA' or x == '29TT' or x == '20X' or x == '29TX' else 'not found' for x in df_sup_2015['ESPAR']]
df_sup_2015['macro_species'] = ['Autre feuillu' if x == '23AB' or x == '23AF' or x == '23AM' or x == '41' or x == '13C' or x == '13G' or x == '13B' or x == '37' or x == '49AA' or x == '49AE' or x == '49AM' or x == '49PA' or x == '29AI' or x == '23A' or x == '40' or x == '49CS' or x == '29AF' or x == '49BO' or x == '49EA' or x == '49BS' or x == '29CA' or x == '29CT' or x == '49CM' or x == '49C' or x == '23C' or x == '39' or x == '38AU' or x == '38AL' or x == '36' or x == '23F' or x == '49FL' or x == '49FA' or x == '29FI' or x == '49EV' or x == '49IA' or x == '49KK' or x == '49LN' or x == '29LI' or x == '49CN' or x == '29MA' or x == '22M' or x == '29MI' or x == '16' or x == '49RA' or x == '49RP' or x == '49RC' or x == '31' or x == '28' or x == '49OB' or x == '49OO' or x == '49CA' or x == '29PT' or x == '29PV' or x == '49PL' or x == '49PT' or x == '29PL' or x == '14' or x == '24' or x == '42' or x == '49VV' or x == '22C' or x == '22G' or x == '22S' or x == '49PM' or x == '49MB' or x == '49MC' or x == '49MN' or x == '23PA' or x == '23PC' or x == '23PF' or x == '49PN' or x == '23PM' or x == '49PC' or x == '49PS' or x == '23PD' or x == '49PB' or x == '49RT' or x == '49SN' or x == '49SR' or x == '11' or x == '32' or x == '10' or x == '27C' or x == '27N' or x == '18C' or x == '18D' or x == '18M' or x == '23SO' or x == '23SF' or x == '23SS' or x == '49TA' or x == '49TF' or x == '49TG' else 'Autre résineux' if x == '68CE' or x == '68CJ' or x == '64' or x == '68TG' or x == '68TC' or x == '68TH' or x == '68TS' or x == '69' or x == '69JC' or x == '69JO' else 'Bouleau' if x == '12P' or x == '12V' else 'Cedre' if x == '65' or x == '68CB' or x == '68CH' or x == '76' else 'Chêne' if x == '2' or x == '3' or x == '4' or x == '5' or x == '6' or x == '7' or x == '08P' or x == '08S' or x == '29CE' or x == '29CM' or x == '34' else 'Cypres' if x == '66' or x == '68CM' or x == '68CA' or x == '68CL' or x == '68CC' else 'Épicéa' if x == '62' or x == '68EO' or x == '73' else 'Érable' if x == '15P' or x == '15S' or x == '21C' or x == '21M' or x == '21O' or x == '29EN' else 'Frêne' if x == '17C' or x == '17F' or x == '17O' or x == '29FA' else 'Hêtre' if x == '9' else 'If' if x == '67' else 'Mélèze' if x == '63' or x == '74J' or x == '74H' else 'Peuplier' if x == '19' or x == '33B' or x == '33G' or x == '33N' else 'Pin' if x == '51' or x == '52' or x == '53CO' or x == '53CA' or x == '53S' or x == '54' or x == '55' or x == '56' or x == '57A' or x == '57B' or x == '58' or x == '59' or x == '60' or x == '68PM' or x == '68PC' or x == '77' else 'Platane' if x == '26E' or x == '26OC' or x == '26OR' else 'Sapin' if x == '61' or x == '68SC' or x == '68SI' or x == '70SE' or x == '70SC' or x == '70SB' or x == '71' or x == '72V' or x == '72N' else 'Saule' if x == '25B' or x == '25M' or x == '25C' or x == '25FD' or x == '25FR' or x == '25D' or x == '25P' or x == '2,50E+06' or x == '25XR' or x == '2,50E+04' or x == '25V' or x == '25R' else 'Séquoia' if x == '68SV' or x == '68SG' else 'Tilleul' if x == '20P' or x == '20G' or x == '29TA' or x == '29TT' or x == '20X' or x == '29TX' else 'not found' for x in df_sup_2015['ESPAR']]
df_sup_2015 = df_sup_2015.loc[df_sup_2015['macro_species'] != 'not found'] 
df_sup_2015 = df_sup_2015.loc[df_sup_2015['Type_a'] != 'not found'] 
df_by_date = df_sup_2015.groupby(['CAMPAGNE'])["Vpondere"].sum().reset_index(name ='TotVolume')
df_by_date_and_type = df_sup_2015.groupby(['CAMPAGNE','Type_a'])["Vpondere"].sum().reset_index(name ='TotVolume')

##### Question 2

The line chart allows a better interpretation of continuity between different timesteps. 
The bar chart allows a better comparison between timesteps, but can be more difficult to read than the linechart in case of a lot of timesteps.

The Y-axis should show the distance between the axis bottom and the 0 value, using a dotted axis segment for example.

In [21]:
line_chart = altair.Chart(df_by_date).mark_line().encode(
    x='CAMPAGNE',
    y=altair.Y('TotVolume', scale=altair.Scale(domain=[500000, 900000]))
).properties(
    width=500
)

bart_chart = altair.Chart(df_by_date).mark_bar(clip=True).encode(
    altair.X("CAMPAGNE", type='ordinal'),
    y=altair.Y('TotVolume', scale=altair.Scale(domain=[500000, 900000]))
).properties(
    width=500
)

line_chart | bart_chart

alt.HConcatChart(...)

##### Question 3

The multi-line chart allows a better comparison between different individuals.
Stacked charts allow a better interpretation of the overall evolution of the dataset, with cumulative evolution.

In [22]:
multi_line_chart = altair.Chart(df_by_date_and_type).mark_line().encode(
    x='CAMPAGNE',
    y=altair.Y('TotVolume', scale=altair.Scale(domain=[250000, 400000])),
    color='Type_a'
).properties(
    width=300
)

stacked_bart_chart = altair.Chart(df_by_date_and_type).mark_bar(clip=True).encode(
    altair.X("CAMPAGNE", type='ordinal'),
    y=altair.Y('TotVolume', scale=altair.Scale(domain=[0, 800000])),
    color='Type_a'
).properties(
    width=300
)

stacked_area_chart = altair.Chart(df_by_date_and_type).mark_area(clip=True).encode(
    altair.X("CAMPAGNE", type='ordinal'),
    y=altair.Y('TotVolume', scale=altair.Scale(domain=[0, 800000])),
    color='Type_a'
).properties(
    width=300
)

multi_line_chart | stacked_bart_chart | stacked_area_chart

alt.HConcatChart(...)

##### Question 3

In [23]:
multi_line_chart_interactive = altair.Chart(df_by_date_and_type).mark_line().encode(
    x='CAMPAGNE',
    y='TotVolume',
    color='Type_a',
    tooltip=[
            altair.Tooltip("Type_a", title="Tree type"),
            altair.Tooltip("TotVolume", title="wood volume"),
            altair.Tooltip("CAMPAGNE", title="year")
        ]
).properties(
    width=300
).interactive()

stacked_bart_chart_interactive = altair.Chart(df_by_date_and_type).mark_bar(clip=True).encode(
    altair.X("CAMPAGNE", type='ordinal'),
    y='TotVolume',
    color='Type_a',
    tooltip=[
            altair.Tooltip("Type_a", title="Tree type"),
            altair.Tooltip("TotVolume", title="wood volume"),
            altair.Tooltip("CAMPAGNE", title="year")
        ]
).properties(
    width=300
).interactive()

stacked_area_chart_interactive = altair.Chart(df_by_date_and_type).mark_area(clip=True).encode(
    altair.X("CAMPAGNE", type='ordinal'),
    y='TotVolume',
    color='Type_a',
    tooltip=[
            altair.Tooltip("Type_a", title="Tree type"),
            altair.Tooltip("TotVolume", title="wood volume"),
            altair.Tooltip("CAMPAGNE", title="year")
        ]
).properties(
    width=300
).interactive()

multi_line_chart_interactive | stacked_bart_chart_interactive | stacked_area_chart_interactive

C:\Users\JGautier.IGN\AppData\Local\Temp\ipykernel_36956\389589517.py:40: UserWarning: Automatically deduplicated selection parameter with identical configuration. If you want independent parameters, explicitly name them differently (e.g., name='param1', name='param2'). See https://github.com/vega/altair/issues/3891
  multi_line_chart_interactive | stacked_bart_chart_interactive | stacked_area_chart_interactive
C:\Users\JGautier.IGN\AppData\Roaming\Python\Python314\site-packages\IPython\core\interactiveshell.py:3701: UserWarning: Automatically deduplicated selection parameter with identical configuration. If you want independent parameters, explicitly name them differently (e.g., name='param1', name='param2'). See https://github.com/vega/altair/issues/3891
  exec(code_obj, self.user_global_ns, self.user_ns)

alt.HConcatChart(...)